// Auto-generated by tools/gen_launcher_art.py -- do not edit.
// Source art: hbmt_load_screen.png -> 1440x1080 BGRX
// in launcher_art.bin (6220800 bytes), bottom 330px pre-darkened.
// The GUI backends embed and expose the pixel data (RCDATA / .incbin).
#pragma once

namespace hb::launcher
{
	constexpr int art_width = 1440;
	constexpr int art_height = 1080;
	constexpr int art_strip_top = 750;
	constexpr int art_bytes = 6220800;
}
