// Auto-generated by version_gen.py — do not edit manually
#pragma once

namespace hb::version
{

namespace compatibility
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 12;
constexpr int build_number = 0;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.12-alpha";
constexpr const char* full_version = "0.2.12-alpha+build.0";
} // namespace compatibility

namespace server
{
constexpr int major = 0;
constexpr int minor = 1;
constexpr int patch = 19;
constexpr int build_number = 191;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.1.19-alpha";
constexpr const char* full_version = "0.1.19-alpha+build.191";
} // namespace server

namespace client
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 47;
constexpr int build_number = 283;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.47-alpha";
constexpr const char* full_version = "0.2.47-alpha+build.283";
} // namespace client

constexpr const char* build_timestamp = "2026-02-26T10:48:13";

} // namespace hb::version
