#!/usr/bin/env python3
"""Generate Sources/Launcher/launcher_art.h from the splash artwork.

Bakes the launcher window backdrop as a raw BGRX pixel array so the launcher
needs no image decoder at runtime (blitted via StretchDIBits on Win32 and an
XImage on X11, both little-endian 32bpp).

Run manually when the artwork changes, then commit the regenerated header:
    python tools/gen_launcher_art.py [path/to/art.png]

Requires Pillow (deliberately NOT a build-time step, unlike version_gen.py,
so ordinary builds carry no Pillow dependency).
"""
import os
import sys

from PIL import Image

ART_DEFAULT = "C:/Users/miste/source/hbmt_load_screen.png"
# Must equal 480x360 * layout::ui_scale (Sources/Launcher/launcher_layout.h)
OUT_WIDTH, OUT_HEIGHT = 1440, 1080
# Bottom strip hosting launcher chrome (status/progress/buttons) is
# pre-darkened here so both GUI backends only draw solid-color widgets on top.
STRIP_HEIGHT = 330   # 110 * ui_scale
STRIP_DARKEN = 0.28  # multiply factor at full strength
STRIP_FADE = 54      # px of gradient easing into the strip (18 * ui_scale)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(REPO_ROOT, "Sources", "Launcher", "launcher_art.h")
# Silver "Helbreath: Medieval Times" logo (alpha-keyed), composited top-center
# like the in-game loading screen. Same proportions: 43% of width, 12% down.
LOGO_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "hbmt_logo.png")
LOGO_WIDTH_FRACTION = 0.43
LOGO_TOP_FRACTION = 0.12


def main():
	art_path = sys.argv[1] if len(sys.argv) > 1 else ART_DEFAULT
	img = Image.open(art_path).convert("RGB").resize((OUT_WIDTH, OUT_HEIGHT), Image.LANCZOS)

	if os.path.exists(LOGO_PATH):
		logo = Image.open(LOGO_PATH).convert("RGBA")
		logo_w = int(OUT_WIDTH * LOGO_WIDTH_FRACTION)
		logo_h = int(logo.height * logo_w / logo.width)
		logo = logo.resize((logo_w, logo_h), Image.LANCZOS)
		img.paste(logo, ((OUT_WIDTH - logo_w) // 2, int(OUT_HEIGHT * LOGO_TOP_FRACTION)), logo)

	px = img.load()
	strip_top = OUT_HEIGHT - STRIP_HEIGHT
	for y in range(strip_top - STRIP_FADE, OUT_HEIGHT):
		if y < strip_top:
			t = (y - (strip_top - STRIP_FADE)) / STRIP_FADE  # 0..1 into the fade
			factor = 1.0 + (STRIP_DARKEN - 1.0) * t
		else:
			factor = STRIP_DARKEN
		for x in range(OUT_WIDTH):
			r, g, b = px[x, y]
			px[x, y] = (int(r * factor), int(g * factor), int(b * factor))

	data = bytearray()
	for y in range(OUT_HEIGHT):
		for x in range(OUT_WIDTH):
			r, g, b = px[x, y]
			data += bytes((b, g, r, 255))  # BGRX little-endian

	# Pixels go into a raw .bin embedded at link time (RCDATA resource on
	# Windows, .incbin on Linux) — a C array this size blows MSVC's heap (C1060).
	bin_path = os.path.join(os.path.dirname(OUT_PATH), "launcher_art.bin")
	with open(bin_path, "wb") as f:
		f.write(data)

	lines = []
	lines.append("// Auto-generated by tools/gen_launcher_art.py -- do not edit.")
	lines.append(f"// Source art: {os.path.basename(art_path)} -> {OUT_WIDTH}x{OUT_HEIGHT} BGRX")
	lines.append(f"// in launcher_art.bin ({len(data)} bytes), bottom {STRIP_HEIGHT}px pre-darkened.")
	lines.append("// The GUI backends embed and expose the pixel data (RCDATA / .incbin).")
	lines.append("#pragma once")
	lines.append("")
	lines.append("namespace hb::launcher")
	lines.append("{")
	lines.append(f"\tconstexpr int art_width = {OUT_WIDTH};")
	lines.append(f"\tconstexpr int art_height = {OUT_HEIGHT};")
	lines.append(f"\tconstexpr int art_strip_top = {strip_top};")
	lines.append(f"\tconstexpr int art_bytes = {len(data)};")
	lines.append("}")

	os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
	with open(OUT_PATH, "w", newline="\n") as f:
		f.write("\n".join(lines) + "\n")

	print(f"wrote {bin_path} ({len(data)} bytes) and {OUT_PATH}")


if __name__ == "__main__":
	main()
